#docker-compose.yml
version: '2.0'    
services:
  novnc:  
      image: psharkey/novnc:latest
      environment:
        # Adjust to your screen size
        - DISPLAY_WIDTH=1600
        - DISPLAY_HEIGHT=968
      ports:
        - "8080:8080"
      networks:
        - x11
  emulator:
    build:
      context: ./
      dockerfile: ./emulator_input_plugin/Dockerfile
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
    restart: always

networks:
  x11: